services:
  instagramclone.api:
    image: ${DOCKER_REGISTRY-}instagramcloneapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    build:
      context: .
      dockerfile: InstagramClone.API/Dockerfile
    ports:
      - "5063:8080"
    depends_on:
      mssql:
        condition: service_healthy
      seq_logs:
        condition: service_started
      redis:
        condition: service_started
    volumes:
      - media_data:/app/wwwroot/media
    networks:
      - app-network
  instagramclone.web:
    image: ${DOCKER_REGISTRY-}instagramcloneweb
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ApiSettings__BaseUrl=http://instagramclone.api:8080
    build:
      context: .
      dockerfile: InstagramClone.Web/Dockerfile
    ports:
      - "5242:8080"
    depends_on:
      - instagramclone.api
    networks:
      - app-network
  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app-network
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql
    hostname: mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"${DB_PASSWORD}\" -C -Q \"SELECT 1\" || /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P \"${DB_PASSWORD}\" -Q \"SELECT 1\""]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    volumes:
      - sqlsystem:/var/opt/mssql
    networks:
      - app-network
  seq_logs:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=password123
    restart: unless-stopped
    ports:
      - "5342:80"
    networks:
      - app-network
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "44391:443"
    depends_on:
      - instagramclone.api
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  sqlsystem:
  media_data:
