---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: instagramapi
    namespace: cloud-native-dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: instagramapi
    spec:
      containers:
      - name: instagramapi
        image: domanh114/instagram-api:latest
        ports:
        - containerPort: 80
        envFrom:
        # Load tất cả key từ ConfigMap thành env vars
        - configMapRef:
            name: instagramapi-config
        # Load tất cả key từ Secret thành env vars
        - secretRef:
            name: instagramapi-secret
  selector:
    matchLabels:
      app: instagramapi
---
apiVersion: v1
kind: Service
metadata:
  name: instagramapi-svc
  namespace: cloud-native-dev
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32001
  selector:
    app: instagramapi

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: instagramapi-scaling
  namespace: cloud-native-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: instagramapi
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 100Mi